import numpy as np
import matplotlib.pyplot as plt
import os
import math
from scipy.interpolate import interp1d
from scipy.interpolate import InterpolatedUnivariateSpline, UnivariateSpline

flying = 'flying'
name = 'results'
arquivos = os.listdir(flying)
x_CMG = np.loadtxt('xCH4_case2MM_CMG.txt')
xCH4_CMG = np.loadtxt('xxCH4_case2MM_CMG.txt')

for  arq in arquivos:
    if  arq.startswith(name):
        '''-----------------------:mUSCL LLF RESULTS------------------------'''

        zCH4_x = np.array([0, 0.246, 0.246, 0.357, 1.101, \
                           1.117, 1.123, 1.138, 1.145, 1.157, \
                           1.163, 1.171, 1.182,1.518, 1.517, 2])
        zCH4 = np.array([1, 1, 0.817, 0.786, 0.786, \
                         0.675, 0.622, 0.540, 0.503, 0.451, \
                         0.421, 0.389, 0.347, 0.330, 0.15, 0.15])
        zCO2_x = np.array([0, 0.245, 0.358, 1.101, 1.116, 1.126, \
                           1.146, 1.159, 1.179, 1.517, 1.519, 2])
        zCO2 = np.array([0, 0, 0, 0, 0.106, 0.171, 0.274, 0.326, \
                         0.391, 0.384, 0.291, 0.287])

        zC10_x = np.array([0, 0.245, 0.246, 0.357, 1.101, 1.152, \
                           1.181, 1.517, 1.517, 2])
        zC10 = np.array([0, 0, 0.187, 0.21, 0.207, 0.223, 0.257, 0.283, \
                         0.56, 0.558])

        'FR2'
        datas = np.load('flying/results_Orr_3k_C514_32x1x1_IMPEC_FR2_LLF_127.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_32_FR2 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_64x1x1_IMPEC_FR2_LLF_255.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_64_FR2 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_128x1x1_IMPEC_FR2_LLF_511.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_128_FR2 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_256x1x1_IMPEC_FR2_LLF_1025.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_256_FR2 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_512x1x1_IMPEC_FR2_LLF_2053.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_512_FR2 = data[10]

        'FR3'
        datas = np.load('flying/results_Orr_3k_C514_32x1x1_IMPEC_FR3_LLF_182.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_32_FR3 = data[10]
            n=32
            x_32 = np.linspace(0+2/(2*n),2*(1-1/(2*n)),n)

        datas = np.load('flying/results_Orr_3k_C514_64x1x1_IMPEC_FR3_LLF_373.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_64_FR3 = data[10]
            n=64
            x_64 = np.linspace(0+2/(2*n),2*(1-1/(2*n)),n)

        datas = np.load('flying/results_Orr_3k_C514_128x1x1_IMPEC_FR3_LLF_769.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_128_FR3 = data[10]
            n=128
            x_128 = np.linspace(0+2/(2*n),2*(1-1/(2*n)),n)

        datas = np.load('flying/results_Orr_3k_C514_256x1x1_IMPEC_FR3_LLF_1557.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_256_FR3 = data[10]
            n=256
            x_256 = np.linspace(0+2/(2*n),2*(1-1/(2*n)),n)

        datas = np.load('flying/results_Orr_3k_C514_512x1x1_IMPEC_FR3_LLF_3148.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_512_FR3 = data[10]
            n=512
            x_512 = np.linspace(0+2/(2*n),2*(1-1/(2*n)),n)

        'FR4'
        datas = np.load('flying/results_Orr_3k_C514_32x1x1_IMPEC_FR4_LLF_240.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_32_FR4 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_64x1x1_IMPEC_FR4_LLF_498.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_64_FR4 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_128x1x1_IMPEC_FR4_LLF_1017.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_128_FR4 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_256x1x1_IMPEC_FR4_LLF_2065.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_256_FR4 = data[10]

        datas = np.load('flying/results_Orr_3k_C514_512x1x1_IMPEC_FR4_LLF_4170.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_512_FR4 = data[10]

        'MUSCL'
        datas = np.load('flying/results_Orr_3k_C514_32x1x1_IMPEC_MUSCL_LLF_123.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_32_MUSCL = data[10]

        datas = np.load('flying/results_Orr_3k_C514_64x1x1_IMPEC_MUSCL_LLF_250.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_64_MUSCL = data[10]

        datas = np.load('flying/results_Orr_3k_C514_128x1x1_IMPEC_MUSCL_LLF_504.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_128_MUSCL = data[10]

        datas = np.load('flying/results_Orr_3k_C514_256x1x1_IMPEC_MUSCL_LLF_1014.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_256_MUSCL = data[10]

        datas = np.load('flying/results_Orr_3k_C514_512x1x1_IMPEC_MUSCL_LLF_2035.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_512_MUSCL = data[10]

        'FOU'
        datas = np.load('flying/results_Orr_3k_C514_32x1x1_IMPEC_FOU_37.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_32_FOU = data[10]

        datas = np.load('flying/results_Orr_3k_C514_64x1x1_IMPEC_FOU_77.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_64_FOU = data[10]

        datas = np.load('flying/results_Orr_3k_C514_128x1x1_IMPEC_FOU_155.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_128_FOU = data[10]

        datas = np.load('flying/results_Orr_3k_C514_256x1x1_IMPEC_FOU_316.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_256_FOU = data[10]

        datas = np.load('flying/results_Orr_3k_C514_512x1x1_IMPEC_FOU_639.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_512_FOU = data[10]

        datas = np.load('flying/results_Orr_3k_C514_8000x1x1_IMPEC_FOU_12084.npy', allow_pickle=True)
        for data in datas[datas.shape[0]-1:]:
            z_8000_FOU = data[10]
            n=8000
            x_8000 = np.linspace(0+2/(2*n),2*(1-1/(2*n)),n)

        plt.figure(36)
        s=3
        plt.plot(x_32, z_32_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        #plt.xlim((0,1.25))
        #plt.ylim((0.6,1.))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_32.png')
        plt.close()

        plt.figure(37)
        s=3
        plt.plot(x_32, z_32_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        plt.xlim((0.2,1.2))
        plt.ylim((0.6,1.01))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_32_zoom1.png')
        plt.close()

        plt.figure(38)
        s=3
        plt.plot(x_32, z_32_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[1,:], ':m', mfc='none')
        plt.plot(x_32, z_32_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        plt.xlim((1.2, 1.6))
        plt.ylim((0.15,0.4))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_32_zoom2.png')
        plt.close()

        plt.figure(39)
        plt.plot(x_32, z_32_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_32.png')
        plt.close()

        plt.figure(40)
        plt.plot(x_32, z_32_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(0.8, 1.25)
        plt.ylim(0.0, 0.3)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_32_zoom1.png')
        plt.close()

        plt.figure(41)
        plt.plot(x_32, z_32_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_32_zoom2.png')
        plt.close()

        plt.figure(42)
        plt.plot(x_32, z_32_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        #plt.plot(x_axis_xCH4_LLF_50, xCH4_LLF_50, '-sk', mfc='none')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_32.png')
        plt.close()

        plt.figure(43)
        plt.plot(x_32, z_32_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_32_zoom1.png')
        plt.close()

        plt.figure(44)
        plt.plot(x_32, z_32_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_32, z_32_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_32, z_32_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 32x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_32_zoom2.png')
        plt.close()


        plt.figure(27)
        s=3
        plt.plot(x_64, z_64_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        #plt.xlim((0,1.25))
        #plt.ylim((0.6,1.))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_64.png')
        plt.close()

        plt.figure(28)
        s=3
        plt.plot(x_64, z_64_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        plt.xlim((0.2,1.2))
        plt.ylim((0.6,1.01))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_64_zoom1.png')
        plt.close()

        plt.figure(29)
        s=3
        plt.plot(x_64, z_64_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[1,:], ':m', mfc='none')
        plt.plot(x_64, z_64_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        plt.xlim((1.2, 1.6))
        plt.ylim((0.15,0.4))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_64_zoom2.png')
        plt.close()

        plt.figure(30)
        plt.plot(x_64, z_64_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_64.png')
        plt.close()

        plt.figure(31)
        plt.plot(x_64, z_64_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(0.8, 1.25)
        plt.ylim(0.0, 0.3)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_64_zoom1.png')
        plt.close()

        plt.figure(32)
        plt.plot(x_64, z_64_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_64_zoom2.png')
        plt.close()

        plt.figure(33)
        plt.plot(x_64, z_64_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        #plt.plot(x_axis_xCH4_LLF_50, xCH4_LLF_50, '-sk', mfc='none')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_64.png')
        plt.close()

        plt.figure(34)
        plt.plot(x_64, z_64_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_64_zoom1.png')
        plt.close()

        plt.figure(35)
        plt.plot(x_64, z_64_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_64, z_64_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_64, z_64_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 64x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_64_zoom2.png')
        plt.close()

        plt.figure(1)
        s=3
        plt.plot(x_128, z_128_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        #plt.xlim((0,1.25))
        #plt.ylim((0.6,1.))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_128.png')
        plt.close()

        plt.figure(10)
        s=3
        plt.plot(x_128, z_128_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        plt.xlim((0.2,1.2))
        plt.ylim((0.6,1.01))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_128_zoom1.png')
        plt.close()

        plt.figure(11)
        s=3
        plt.plot(x_128, z_128_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[1,:], ':m', mfc='none')
        plt.plot(x_128, z_128_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.grid()
        plt.xlim((1.2, 1.6))
        plt.ylim((0.15,0.4))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_128_zoom2.png')
        plt.close()

        plt.figure(2)
        plt.plot(x_128, z_128_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_128.png')
        plt.close()

        plt.figure(12)
        plt.plot(x_128, z_128_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(0.8, 1.25)
        plt.ylim(0.0, 0.3)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_128_zoom1.png')
        plt.close()

        plt.figure(13)
        plt.plot(x_128, z_128_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_128_zoom2.png')
        plt.close()

        plt.figure(3)
        plt.plot(x_128, z_128_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        #plt.plot(x_axis_xCH4_LLF_50, xCH4_LLF_50, '-sk', mfc='none')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_128.png')
        plt.close()

        plt.figure(13)
        plt.plot(x_128, z_128_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_128_zoom1.png')
        plt.close()

        plt.figure(14)
        plt.plot(x_128, z_128_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_128, z_128_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_128, z_128_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 128x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_128_zoom2.png')
        plt.close()

        plt.figure(4)
        plt.plot(x_256, z_256_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')

        plt.grid()
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_256.png')
        plt.close()

        plt.figure(15)
        plt.plot(x_256, z_256_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.xlim((0.2,1.2))
        plt.ylim((0.6,1.01))
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_256_zoom1.png')
        plt.close()

        plt.figure(16)
        plt.plot(x_256, z_256_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.xlim((1.2, 1.6))
        plt.ylim((0.15,0.4))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_256_zoom2.png')
        plt.close()

        plt.figure(5)
        plt.plot(x_256, z_256_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_256.png')
        plt.close()

        plt.figure(17)
        plt.plot(x_256, z_256_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.xlim(0.8, 1.25)
        plt.ylim(0.0, 0.3)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_256_zoom1.png')
        plt.close()

        plt.figure(18)
        plt.plot(x_256, z_256_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_256_zoom2.png')
        plt.close()

        plt.figure(6)
        plt.plot(x_256, z_256_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_256.png')
        plt.close()

        plt.figure(19)
        plt.plot(x_256, z_256_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_256_zoom.png')
        plt.close()

        plt.figure(20)
        plt.plot(x_256, z_256_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_256, z_256_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_256, z_256_FR4[2,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        #plt.plot(zC10_x, zC10, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 256x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_256_zoom2.png')
        plt.close()

        plt.figure(7)
        plt.plot(x_512, z_512_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_512.png')
        plt.close()

        plt.figure(21)
        plt.plot(x_512, z_512_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.xlim((0.2,1.2))
        plt.ylim((0.6,1.01))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_512_zoom1.png')
        plt.close()

        plt.figure(22)
        plt.plot(x_512, z_512_FOU[1,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[1,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[1,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[1,:], '-y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[1,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[1,:], '-k', linewidth=2)
        #plt.plot(zCH4_x, zCH4, '-k')
        plt.xlim((1.2, 1.6))
        plt.ylim((0.15,0.4))
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.grid()
        plt.ylabel('$z_{C1}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C1_orr_C514_NVCM_512_zoom2.png')
        plt.close()

        plt.figure(8)
        plt.plot(x_512, z_512_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_512.png')
        plt.close()

        plt.figure(23)
        plt.plot(x_512, z_512_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(0.8, 1.25)
        plt.ylim(0.0, 0.3)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_512_zoom1.png')
        plt.close()

        plt.figure(24)
        plt.plot(x_512, z_512_FOU[0,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[0,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[0,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[0,:], '-y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[0,:], '--r', mfc='none', markersize=s)
        plt.plot(x_8000, z_8000_FOU[0,:], '-k', linewidth=2)
        #plt.plot(zCO2_x, zCO2, '-k')
        plt.grid()
        plt.xlim(1.1, 1.6)
        plt.ylim(0.27, 0.405)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.ylabel('$z_{CO_2}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_CO2_orr_C514_NVCM_512_zoom2.png')
        plt.close()

        plt.figure(9)
        plt.plot(x_512, z_512_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[2,:], '-.g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[2,:], '-y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[2,:], '--r', mfc='none', markersize=s)
        #plt.plot(zC10_x, zC10, '-k')
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        #plt.xlim(0.2,1.5)
        #plt.ylim(0.15,0.3)
        #plt.plot(x_axis_xCH4_LLF_50, xCH4_LLF_50, '-sk', mfc='none')
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_512.png')
        plt.close()

        plt.figure(25)
        plt.plot(x_512, z_512_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[2,:], '-g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[2,:], '-.y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[2,:], '--r', mfc='none', markersize=s)
        #plt.plot(zC10_x, zC10, '-k')
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.xlim(0.25,1.5)
        plt.ylim(0.2,0.3)
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_512_zoom1.png')
        plt.close()

        plt.figure(26)
        plt.plot(x_512, z_512_FOU[2,:], '-..b', mfc='none', markersize=s)
        plt.plot(x_512, z_512_MUSCL[2,:], ':m', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR2[2,:], '-g', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR3[2,:], '-.y', mfc='none', markersize=s)
        plt.plot(x_512, z_512_FR4[2,:], '--r', mfc='none', markersize=s)
        #plt.plot(zC10_x, zC10, '-k')
        plt.plot(x_8000, z_8000_FOU[2,:], '-k', linewidth=2)
        plt.legend(('FOU', 'MUSCL', 'FR-P1', 'FR-P2', 'FR-P3', 'Reference'))
        plt.title('Results for 512x1x1 mesh')
        plt.xlim(0.25,1.5)
        plt.ylim(0.2,0.3)
        plt.grid()
        plt.ylabel('$z_{C10}$')
        plt.xlabel('Distance')
        plt.savefig('results/compositional/3k_C10_orr_C514_NVCM_512_zoom2.png')
        plt.close()
        import pdb; pdb.set_trace()
